# Generated by Django 5.2.9 on 2026-04-13 07:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('from_email', models.EmailField(default='marketing@sophicservices.com', max_length=254)),
                ('to_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255), blank=True, null=True, size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255), blank=True, null=True, size=None)),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255), blank=True, null=True, size=None)),
                ('subject', models.TextField(blank=True, null=True)),
                ('html_message', models.TextField()),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('error_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'In-Progress'), (3, 'Sent'), (4, 'Error')], default=1)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
