# Generated by Django 5.2.9 on 2026-04-13 07:30

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Plan Price in USD')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Is Custom')),
                ('can_change', models.BooleanField(default=True, verbose_name='Can Change')),
                ('information', models.TextField(blank=True, default='Our Plan offers the flexibility of unlimited checks tailored to your specific needs, perfect for both individuals and small businesses seeking reliable, continuous access to our services. Additionally, you can save more with a commitment-based pricing model, designed for those who want to maximize value with long-term usage.', null=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('credit', models.PositiveBigIntegerField(default=0)),
                ('subscription_period', models.PositiveSmallIntegerField(choices=[(1, 'One Week'), (2, 'One Month'), (3, 'One Year'), (4, 'Custom')], default=4, verbose_name='Subscription Period')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('referral_code', models.CharField(blank=True, default='GTZ8ZX', max_length=6, null=True)),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Referral Expire Date')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('referral_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL, verbose_name='Referral User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to=settings.AUTH_USER_MODEL, verbose_name='Referred By')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_plan', to='subscription.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Referral Plan Code',
                'verbose_name_plural': 'Referral Plan Code',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PackageDescription',
            fields=[
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('subscription_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_descriptions', to='subscription.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Package Description',
                'verbose_name_plural': 'Package Description',
            },
        ),
        migrations.CreateModel(
            name='ClientPlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Stripe'), (2, 'Paypal')], default=1, verbose_name='Plan Type')),
                ('plan_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount')),
                ('tax', models.CharField(blank=True, max_length=50, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custsubsdetails', to='subscription.subscriptionpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCreditSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('invoice', models.CharField(default=223641228306106, max_length=256)),
                ('activated_on', models.DateTimeField(auto_now_add=True, verbose_name='Activated On')),
                ('plan_data', models.JSONField(blank=True, null=True)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Debit Card'), (4, 'Credit Card'), (5, 'Internet Banking'), (6, 'Stripe Subscription'), (7, 'Stripe Charge'), (8, 'Paypal Subscription')], default=1, verbose_name='Payment Method')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'One Time'), (2, 'Recurring Payment')], db_index=True, default=1, verbose_name='Payment Type')),
                ('payment_receipt', models.FileField(blank=True, max_length=500, null=True, upload_to='payments/', verbose_name='Payment Receipt')),
                ('acknowledgement', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire Date')),
                ('is_current', models.BooleanField(default=True, verbose_name='Is Current')),
                ('cust_subscription', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_charge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('renews_on', models.DateTimeField(blank=True, null=True, verbose_name='Renews on')),
                ('recurring_data', models.JSONField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('plan_updated', models.BooleanField(default=False)),
                ('cancellation_comment', models.TextField(blank=True, null=True)),
                ('latest_receipt_url', models.TextField(blank=True, null=True)),
                ('latest_invoice_id', models.TextField(blank=True, null=True)),
                ('latest_charge_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('total_credit', models.PositiveBigIntegerField(default=0)),
                ('credit_balance', models.PositiveBigIntegerField(default=0)),
                ('credit_reserved', models.PositiveBigIntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('client', models.ForeignKey(limit_choices_to={'user_role__role': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='client_credits', to='accounts.clientuser', verbose_name='Client')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_plans', to='subscription.subscriptionpackage', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('cust_transaction_data', models.JSONField(blank=True, null=True)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Subscription\xa0Purchase'), (2, 'Subscription\xa0Renewal'), (3, 'Client\xa0Revenue')], default=1, verbose_name='Transaction\xa0Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total overage charges in CAD')),
                ('receipt_url', models.CharField(blank=True, max_length=300, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Debit Card'), (4, 'Credit Card'), (5, 'Internet Banking'), (6, 'Stripe Subscription'), (7, 'Stripe Charge'), (8, 'Paypal Subscription')], default=6, verbose_name='Payment Method')),
                ('payment_receipt', models.FileField(blank=True, max_length=500, null=True, upload_to='payments/', verbose_name='Payment Receipt')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_transactions', to='subscription.clientcreditsubscription', verbose_name='Customer\xa0Subscription')),
            ],
            options={
                'verbose_name': 'Overrage Transaction Fee (Offline)',
                'verbose_name_plural': 'Overrage Transaction Fees (Offline)',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
