# Generated by Django 5.2.9 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditsubscription',
            name='invoice',
            field=models.CharField(default=191816866050146, max_length=256),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referral_code',
            field=models.CharField(blank=True, default='A0UM4Y', max_length=6, null=True),
        ),
    ]
