# Generated by Django 5.2.9 on 2026-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_clientcreditsubscription_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditsubscription',
            name='invoice',
            field=models.CharField(default=236607665131597, max_length=256),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referral_code',
            field=models.CharField(blank=True, default='BSVN3C', max_length=6, null=True),
        ),
    ]
