# Generated by Django 5.2.9 on 2026-05-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_clientcreditsubscription_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditsubscription',
            name='invoice',
            field=models.CharField(default=243966906015495, max_length=256),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referral_code',
            field=models.CharField(blank=True, default='BZPIB0', max_length=6, null=True),
        ),
    ]
