"""
Django settings for checkemails project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os, time
from pathlib import Path
from .celery import *
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(os.environ.get('PROJECT_ROOT', Path(__file__).resolve().parent.parent.parent))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xy#^%zd42et861zw4761zgp-94mp0con&hcs5yxqga#59q%yc#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    "daphne",
    'checkemails.apps.CheckEmailsAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.flatpages',
]

THIRD_PARTY_APP = [
    'mathfilters',   
    "import_export_celery",
    'import_export',
    'debug_toolbar',    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', 
    'impersonate',
    'rest_framework',
    'django_filters',
    'channels',
    ]

LOCAL_APPS = [
    'accounts',
    'core',
    'log',
    'leads',
    'subscription',
    'support',
    'tools',
]

INSTALLED_APPS += THIRD_PARTY_APP + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    "impersonate.middleware.ImpersonateMiddleware",
]

ROOT_URLCONF = 'checkemails.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'checkemails.core.context_processors.load_user_data'
            ],
        },
    },
]

WSGI_APPLICATION = 'checkemails.wsgi.application'

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('CHECK_EMAILS_DATABASE_NAME'),
        'USER': os.environ.get('CHECK_EMAILS_DATABASE_USER'),
        'PASSWORD': os.environ.get('CHECK_EMAILS_DATABASE_PASSWORD'),
        'HOST': os.environ.get('CHECK_EMAILS_DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('CHECK_EMAILS_DATABASE_PORT', 5432),
    }
}


AUTH_USER_MODEL = 'accounts.User'
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


STATIC_ROOT = os.path.join(BASE_DIR, 'public', 'static' )

MEDIA_ROOT = os.path.join(BASE_DIR, 'public', 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get('CHECK_EMAILS_EMAIL_HOST')
EMAIL_PORT = os.environ.get('CHECK_EMAILS_EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('CHECK_EMAILS_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('CHECK_EMAILS_EMAIL_HOST_PASSWORD')
EMAIL_DEFAULT = 'marketing@sophicservices.com'


SESSION_COOKIE_AGE = 1296000 # 15 days to seconds


LIST_APP_FOR_LOGGING = [
    'accounts',
    'log',
    'leads',
    'tools',
    'subscription',
]


PAGINATION_PAGE_SIZE = 20


DEFAULT_LOGIN = 'accounts:login'
DEFAULT_LOGOUT = 'accounts:logout'

LOGIN_URL = 'accounts:login'

LOGIN_REDIRECT_URL = 'subscription:plan_check'

ADMINS = (
    ('Gagandeep', 'gagandeep.singh@sophicservices.com')
)

MANAGERS = ADMINS
CELERY_TIMEZONE = 'Asia/Kolkata'
TIME_ZONE = 'Asia/Kolkata'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_LOGOUT_ON_GET= True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL
SOCIAL_AUTH_LOGIN_ERROR_URL = SOCIAL_AUTH_LOGIN_URL = SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = SOCIAL_AUTH_INACTIVE_USER_URL  = LOGIN_URL

# ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'
PAYMENT_RECEIPT_PATH = 'payments/'



SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'

PAYPAL_CLIENT_ID='ASL21awWRBeIlGYZIUVrAj8IYApuKaRBkAV44BsmbbjZwTYFj2MwU6cwmi9bTTi8u0xwu8kRndkaWEs0'
PAYPAL_CLIENT_SECRET="EKCI-j9EUtVLTHxvWuEJv3CVCQ_2JzIM7okVYpEJT2CuFi_gO-VdtP-Wf0WJr-7zpo8uY1ae0noz_8OG"


STRIPE_CLIENT_ID='acct_1OoPsTEnFDB0iJfZ'
STRIPE_SECRET_KEY='sk_test_51OoPsTEnFDB0iJfZzmzCebwhmOpTzu1ySCVFP838RlAmEFhliYpjFjJ65HrsSjqwgAjFVhGwQlcatJYrE8Ds0OQl003I8cSIxM'
STRIPE_PUBLISHABLE_KEY='pk_test_51OoPsTEnFDB0iJfZncxGHbNF6A49ZONFTyL2UhJBVb9Pk2gDzJhpv4PLT5pHCLUxYNK9hguw2pc3L3Rb58Juae7w00Pdp4xMRA'

REQUIRE_SUPERUSER = False
USE_HTTP_REFERER = True

IMPERSONATE = {
    'REDIRECT_FIELD_NAME': 'next',
    'SEARCH_FIELDS': ['full_name', 'email',]
    }

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'checkemails.core.renderers.ApiRenderer',
    ),
    'EXCEPTION_HANDLER': 'checkemails.core.exceptions.api_exception_handler',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    
}

ASGI_APPLICATION = 'checkemails.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "credit":{
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2"
    }
}

CELERY_TASK_SOFT_TIME_LIMIT = 82800
CELERY_TASK_TIME_LIMIT      = 86400

CSRF_TRUSTED_ORIGINS = [
    "https://checkemails.io",
]

ZYTE_API_KEY = os.environ.get('ZYTE_API_KEY','')
