# Generated by Django 5.2.9 on 2026-04-13 07:30

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(help_text='Please enter a 10 digit mobile number.', max_length=20, verbose_name='Contact Number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False)),
                ('google_user', models.BooleanField(default=False)),
                ('contact_full_name', models.CharField(max_length=100, verbose_name='Billing Name')),
                ('contact_address', models.CharField(max_length=100, verbose_name='Billing Address')),
                ('contact_phone', models.CharField(max_length=100, verbose_name='Billing Phone')),
                ('contact_city', models.CharField(max_length=100, verbose_name='Billing City')),
                ('contact_country', models.CharField(max_length=100, verbose_name='Billing Country')),
                ('contact_province', models.CharField(max_length=100, verbose_name='Billing City')),
                ('contact_postal_code', models.CharField(max_length=100, verbose_name='Billing Postal Code')),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('has_plan', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client(s)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Manager(s)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team(s)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('balance_notify', models.BooleanField(default=True)),
                ('email_notify', models.BooleanField(default=True)),
                ('terms', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('role', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Team'), (4, 'Client')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userrole', verbose_name='User Role'),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('expire_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('extras', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.PositiveSmallIntegerField(choices=[(1, 'Forgot password OTP'), (2, 'Forgot password Link')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
