# Generated by Django 5.2.9 on 2026-04-13 07:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceJob',
            fields=[
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Bulk'), (3, 'Website'), (4, 'Lead')])),
                ('source_reference', models.FileField(blank=True, max_length=500, null=True, upload_to='source-reference/', verbose_name='Source Reference')),
                ('source_format', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Verifying'), (5, 'Verified'), (4, 'Failed'), (6, 'Upload Failed')], default=1)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_duplicate', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('risky_count', models.PositiveIntegerField(default=0)),
                ('syntax_invalid_count', models.PositiveIntegerField(default=0)),
                ('role_based_count', models.PositiveIntegerField(default=0)),
                ('disposable_count', models.PositiveIntegerField(default=0)),
                ('catch_all_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('upload_completed', models.BooleanField(default=False)),
                ('upload_started_at', models.DateTimeField(auto_now_add=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_row_label', models.BooleanField(default=False)),
                ('duplicate_confirm', models.BooleanField(default=False)),
                ('selected_file_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('finalize_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Data Source Job',
                'verbose_name_plural': 'Data Source Jobs',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('input_value', models.CharField(max_length=255)),
                ('result_data', models.JSONField(default=dict)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Verifying'), (4, 'Verified'), (5, 'Failed')], default=1)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_items', to='tools.datasourcejob')),
            ],
            options={
                'verbose_name': 'Data Source Item',
                'verbose_name_plural': 'Data Source Items',
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('email', models.EmailField(max_length=254)),
                ('valid', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('code', models.IntegerField(default=204)),
                ('email_result', models.CharField(max_length=500)),
                ('disposable', models.BooleanField(default=False)),
                ('professional', models.BooleanField(default=False)),
                ('domain_age', models.IntegerField(default=0)),
                ('has_domain_mx', models.BooleanField(default=False)),
                ('has_dmarc', models.BooleanField(default=False)),
                ('has_spf', models.BooleanField(default=False)),
                ('has_smtp', models.BooleanField(default=False)),
                ('role_based', models.BooleanField(default=False)),
                ('retry_later', models.BooleanField(default=False)),
                ('catch_all', models.BooleanField(default=False)),
                ('permanent_failure', models.BooleanField(default=False)),
                ('needs_manual_review', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Ok'), (2, 'Invalid'), (3, 'Risky'), (4, 'Catch All'), (7, 'Disposable'), (5, 'Unknown'), (6, 'Syntax error')], default=5)),
                ('quality', models.PositiveIntegerField(choices=[(5, 'Unknown'), (2, 'Invalid'), (1, 'Valid'), (3, 'Risky')], default=5)),
                ('email_source', models.PositiveIntegerField(choices=[(1, 'SMTP'), (2, 'Swaks'), (3, 'Scraped'), (4, 'Manual'), (5, 'Social')], default=4)),
                ('email_type', models.PositiveIntegerField(choices=[(8, 'Professional'), (9, 'Webmail'), (7, 'Disposable'), (5, 'Unknown')], default=5)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Email Data',
            },
        ),
        migrations.CreateModel(
            name='LeadFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('social_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=500, null=True), blank=True, default=list, null=True, size=None)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_finders', to='tools.emaildata')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScraperResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('url', models.TextField()),
                ('final_url', models.TextField(blank=True, null=True)),
                ('scrape_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emaildata', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None)),
                ('scrapedata', models.JSONField(default=dict)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tools.datasourceitem')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tools.datasourcejob')),
            ],
            options={
                'ordering': ['id'],
            },
            managers=[
                ('without_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(choices=[('pushy', 'Pushy'), ('crafty', 'Crafty'), ('overcommit', 'Overcommit'), ('monetary', 'Monetary'), ('notnatural', 'Not natural')], max_length=255, unique=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Spam Category',
                'verbose_name_plural': 'Spam Categories',
            },
        ),
        migrations.CreateModel(
            name='SpamKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('keyword', models.CharField(max_length=255)),
                ('regex_pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_%(class)ss_to', to=settings.AUTH_USER_MODEL, verbose_name='Belongs To')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.spamcategory')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Spam Keyword',
                'verbose_name_plural': 'Spam Keywords',
            },
        ),
        migrations.AddIndex(
            model_name='datasourceitem',
            index=models.Index(fields=['source_job'], name='tools_datas_source__9befef_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourceitem',
            index=models.Index(fields=['result_data'], name='tools_datas_result__5ecfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourceitem',
            index=models.Index(fields=['status'], name='tools_datas_status_74351d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scraperresult',
            unique_together={('source_job', 'url')},
        ),
    ]
