# Generated by Django 5.2.9 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasourceitem',
            options={'ordering': ['-create_date'], 'verbose_name': 'Data Source Item', 'verbose_name_plural': 'Data Source Items'},
        ),
        migrations.AlterModelOptions(
            name='datasourcejob',
            options={'ordering': ['-create_date'], 'verbose_name': 'Data Source Job', 'verbose_name_plural': 'Data Source Jobs'},
        ),
        migrations.AlterField(
            model_name='datasourceitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'In Progress'), (4, 'Completed'), (5, 'Failed')], default=1),
        ),
    ]
