# Generated by Django 5.2.9 on 2026-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_datasourceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcejob',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'In Progress'), (5, 'Completed'), (4, 'Failed'), (6, 'Upload Failed')], default=1),
        ),
    ]
